import { EditBaseType } from './edit-types/edit-base-type';
import { EditBooleanType } from './edit-types/edit-boolean-type';
import { EditDateTimeType } from './edit-types/edit-date-time-type';
import { EditNumberEnumType } from './edit-types/edit-number-enum-type';
import { EditNumberRemoteSelectType } from './edit-types/edit-number-remote-select-type';
import { EditNumberType } from './edit-types/edit-number-type';
import { EditStringColorType } from './edit-types/edit-string-color-type';
import { EditStringEnumType } from './edit-types/edit-string-enum-type';
import { EditStringFileType } from './edit-types/edit-string-file';
import { EditStringImageType } from './edit-types/edit-string-image';
import { EditStringJoditEditorType } from './edit-types/edit-string-jodit-type';
import { EditStringRemoteSelectType } from './edit-types/edit-string-remote-select-type';
import { EditStringTextareaType } from './edit-types/edit-string-textarea-type';
import { EditStringType } from './edit-types/edit-string-type';
import { ListBaseType } from './list-types/list-base-type';
import { ListBooleanType } from './list-types/list-boolean-type';
import { ListNumberEnumType } from './list-types/list-number-enum-type';
import { ListNumberRemoteSelectType } from './list-types/list-number-remote-select-type';
import { ListStringEnumType } from './list-types/list-string-enum-type';
import { ListStringImageType } from './list-types/list-string-image-type';
import { ListStringRemoteSelectType } from './list-types/list-string-remote-select-type';
export declare const EditTypes: {
    EditBaseType: typeof EditBaseType;
    EditBooleanType: typeof EditBooleanType;
    EditDateTimeType: typeof EditDateTimeType;
    EditNumberEnumType: typeof EditNumberEnumType;
    EditNumberRemoteSelectType: typeof EditNumberRemoteSelectType;
    EditNumberType: typeof EditNumberType;
    EditStringColorType: typeof EditStringColorType;
    EditStringEnumType: typeof EditStringEnumType;
    EditStringFileType: typeof EditStringFileType;
    EditStringImageType: typeof EditStringImageType;
    EditStringJoditEditorType: typeof EditStringJoditEditorType;
    EditStringRemoteSelectType: typeof EditStringRemoteSelectType;
    EditStringTextareaType: typeof EditStringTextareaType;
    EditStringType: typeof EditStringType;
};
export declare const ListTypes: {
    ListBaseType: typeof ListBaseType;
    ListBooleanType: typeof ListBooleanType;
    ListNumberEnumType: typeof ListNumberEnumType;
    ListNumberRemoteSelectType: typeof ListNumberRemoteSelectType;
    ListStringEnumType: typeof ListStringEnumType;
    ListStringImageType: typeof ListStringImageType;
    ListStringRemoteSelectType: typeof ListStringRemoteSelectType;
};
